swiftmailer:
    transport: '%env(MAILER_TRANSPORT)%'
    host: '%env(MAILER_HOST)%'
    username: '%env(MAILER_USER)%'
    password: '%env(MAILER_PASSWORD)%'
    port: '%env(MAILER_PORT)%'
    encryption: '%env(MAILER_ENCRYPTION)%'
    spool: { type: memory }

