twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        "%kernel.project_dir%/src/Resources/FOSOAuthServerBundle/views": FOSOAuthServerBundle
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        default_locale: '%kernel.default_locale%'
        supported_locales: '%supported_locales%'
        texts: '@App\Services\Texts'
        allow_search_engine_tracking: '%allow_search_engine_tracking%'
        discord_invite: '%discord_invite%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
